/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex003;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author franz
 */
public class AppointmentDlg extends javax.swing.JDialog {

    /**
     * Creates new form AppointmentDlg
     */
    
    private boolean isOk;
    
    public AppointmentDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        isOk = false;
        initComponents();
    }
    
    public boolean isOk()
    {
        return isOk;
    }
    
    public Appointment getAppointment()
    {
        try{
            int day = Integer.parseInt(tfDay.getText());
            int month = Integer.parseInt(tfMonth.getText());
            int year = Integer.parseInt(tfYear.getText());
            int hour = Integer.parseInt(tfHour.getText());
            int minute = Integer.parseInt(tfMinute.getText());
            
            LocalDateTime ldt = LocalDateTime.of(year, month, day, hour, minute);
            String text = tfText.getText();
            
            return new Appointment(ldt, text);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Fehler im Datum", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfDay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMonth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfYear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfHour = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        bnOK = new javax.swing.JButton();
        bnNotOK = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tag:");
        getContentPane().add(jLabel1);

        tfDay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDayActionPerformed(evt);
            }
        });
        getContentPane().add(tfDay);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Monat:");
        getContentPane().add(jLabel2);

        tfMonth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfMonth);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Jahr:");
        getContentPane().add(jLabel3);

        tfYear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfYear);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Stunde:");
        getContentPane().add(jLabel4);

        tfHour.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfHour);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Minute:");
        getContentPane().add(jLabel6);

        tfMinute.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfMinute);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Text:");
        getContentPane().add(jLabel7);

        tfText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(tfText);

        bnOK.setText("Übernehmen");
        bnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOK(evt);
            }
        });
        getContentPane().add(bnOK);

        bnNotOK.setText("Abbrechen");
        bnNotOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        getContentPane().add(bnNotOK);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDayActionPerformed

    private void onOK(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOK
        isOk = true;
        this.setVisible(false);
    }//GEN-LAST:event_onOK

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        isOk = false;
        this.setVisible(false);
    }//GEN-LAST:event_onCancel

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppointmentDlg dialog = new AppointmentDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnNotOK;
    private javax.swing.JButton bnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfDay;
    private javax.swing.JTextField tfHour;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfText;
    private javax.swing.JTextField tfYear;
    // End of variables declaration//GEN-END:variables
}
